FROM openjdk:11-jre

EXPOSE 8080

ENV JAVA_OPTS=

COPY docker/ /
RUN mkdir -p /docker-entrypoint.d
ENTRYPOINT [ "/docker-entrypoint.sh" ]

ADD ./modules/services/ogc-api-records/target/gn-ogc-api-records.jar /opt/app/gn-ogc-api-records.jar

CMD exec java $JAVA_OPTS -jar /opt/app/gn-ogc-api-records.jar
